### PR TITLE
Update CodeSystemMedicationStatusCodes.swift

### PR DESCRIPTION
**Pull request by jkiddo**
Align the codes with the standard - taken from https://www.hl7.org/fhir/codesystem-medication-statement-status.html

### CODE REVIEW

**Comment by jkiddo** [comment]
@p2-apple x-mas comes early this year

**Comment by p2-apple** [comment]
Thanks for these, Jens, but these are all auto-generated, we can't accept changes individually. I'll re-run generation soon to account for these changes.

**Comment by p2-apple** [comment]
Hmmm, I wonder why these are not up to date, though.

**Comment by jkiddo** [comment]
Me too

**Comment by xinsight** [comment]
https://www.hl7.org/fhir/codesystem-medication-status.html
vs
https://www.hl7.org/fhir/codesystem-medication-statement-status.html

**Comment by p2-apple** [comment]
Ah of course, thanks @xinsight ! @jkiddo , what you want is https://github.com/apple/FHIRModels/blob/main/Sources/ModelsR4/CodeSystemMedicationStatementStatusCodes.swift

**Comment by jkiddo** [comment]
@p2-apple @xinsight - You guys are correct in regards to the CodeSystem. However, it looks like the MedicationStatement.status is bound to the wrong status field - being https://github.com/apple/FHIRModels/blob/c91e5bb74397136f79656bebdfda76a523d3e88c/Sources/ModelsR4/CodeSystemMedicationStatusCodes.swift instead of https://github.com/apple/FHIRModels/blob/c91e5bb74397136f79656bebdfda76a523d3e88c/Sources/ModelsR4/CodeSystemMedicationStatementStatusCodes.swift from what I can see on https://github.com/apple/FHIRModels/blob/c91e5bb74397136f79656bebdfda76a523d3e88c/Sources/ModelsR4/MedicationStatement.swift#L68

**Comment by p2-apple** [comment]
Thank you! Converted to #11

**Pull request closed without merging**
